In [1]:
import numpy as np

In [4]:
a=np.array([[1],[2],[3]])
b=np.ones((3,3))
print(a)
print(b)

[[1]
 [2]
 [3]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
c=a+b
print(c)

[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [12]:
print('sum of axis1= horizontally: ',c.sum(axis=1,keepdims=True))

sum of axis1= horizontally:  [[ 6.]
 [ 9.]
 [12.]]


In [13]:
d = np.array([1,2,3])
print(d)

[1 2 3]


In [14]:
d+c

array([[3., 4., 5.],
       [4., 5., 6.],
       [5., 6., 7.]])

In [16]:
print(a)
print(d)
print(a.dot(d.reshape((1,3))))
print(d.dot(a))

[[1]
 [2]
 [3]]
[1 2 3]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[14]
